### upload image
POST localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDA0NzY5MDEsImV4cCI6MTc0MDQ4NDEwMSwiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiYzFjMDVmNmMtMGRjNC00ZDVmLTk4NjQtMDJkZjFkODRhYjRlIiwidXNlcm5hbWUiOiJzYW5qYXI5MDIxMDVAZ21haWwuY29tIiwicm9sZSI6WyJST0xFX1VTRVIiXX0.R9hInKIf6ezfUqJoLOPG65fpHzFYDKKvuYn-6bYe0riNxFqW4rOiKPQ3AomitXaE

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename=sanjarGr.jpg

< C:\Users\Sanjar\Desktop\sanjarGr.jpg