### update details
PUT localhost:8080/api/v1/profile/detail
Content-Type: application/json
Accept-Language: ru
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDAzOTkxMDIsImV4cCI6MTc0MDQwNjMwMiwiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiMjgyZDNhMWYtYTE0Yy00MWNiLTlhMzYtNGY2MmFhZDI2OTY2IiwidXNlcm5hbWUiOiJydW5uZXJwcm8xOTkwQGdtYWlsLmNvbSIsInJvbGUiOlsiUk9MRV9VU0VSIl19.KgA50pO8kWizbafyXAPMwD_XBYpukWbmQMqPgv97gz2CPWPARcplSl9t-92asDwV

{
  "name": "Name updated"
}
### update password
PUT localhost:8080/api/v1/profile/password
Content-Type: application/json
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDAzOTkxMDIsImV4cCI6MTc0MDQwNjMwMiwiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiMjgyZDNhMWYtYTE0Yy00MWNiLTlhMzYtNGY2MmFhZDI2OTY2IiwidXNlcm5hbWUiOiJydW5uZXJwcm8xOTkwQGdtYWlsLmNvbSIsInJvbGUiOlsiUk9MRV9VU0VSIl19.KgA50pO8kWizbafyXAPMwD_XBYpukWbmQMqPgv97gz2CPWPARcplSl9t-92asDwV

{
  "currentPassword": "1234567",
  "newPassword": "123456"
}
### update username
PUT localhost:8080/api/v1/profile/updateUsername
Content-Type: application/json
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDA0NzY5MDEsImV4cCI6MTc0MDQ4NDEwMSwiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiYzFjMDVmNmMtMGRjNC00ZDVmLTk4NjQtMDJkZjFkODRhYjRlIiwidXNlcm5hbWUiOiJzYW5qYXI5MDIxMDVAZ21haWwuY29tIiwicm9sZSI6WyJST0xFX1VTRVIiXX0.R9hInKIf6ezfUqJoLOPG65fpHzFYDKKvuYn-6bYe0riNxFqW4rOiKPQ3AomitXaE

{
  "username": "998908070176"
}

### update username confirm
PUT localhost:8080/api/v1/profile/updateUsername/confirm
Content-Type: application/json
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDA0NzY5MDEsImV4cCI6MTc0MDQ4NDEwMSwiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiYzFjMDVmNmMtMGRjNC00ZDVmLTk4NjQtMDJkZjFkODRhYjRlIiwidXNlcm5hbWUiOiJzYW5qYXI5MDIxMDVAZ21haWwuY29tIiwicm9sZSI6WyJST0xFX1VTRVIiXX0.R9hInKIf6ezfUqJoLOPG65fpHzFYDKKvuYn-6bYe0riNxFqW4rOiKPQ3AomitXaE

{
  "code": "20435"
}
### update photo
PUT localhost:8080/api/v1/profile/updatePhoto
Content-Type: application/json
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDA0OTg1NDQsImV4cCI6MTc0MDUwNTc0NCwiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiMjgyZDNhMWYtYTE0Yy00MWNiLTlhMzYtNGY2MmFhZDI2OTY2IiwidXNlcm5hbWUiOiJydW5uZXJwcm8xOTkwQGdtYWlsLmNvbSIsInJvbGUiOlsiUk9MRV9VU0VSIl19.x-xIGN5nmQRZMdMMqRPth82CSkEssJpAyIpOBkbppa6_e7oKz3OF8zN77F8hCfXo

{
"attachId": "77f7e254-8840-4b7f-8491-c7dd4793aba9.jpg"
}

### filter profile
POST localhost:8080/api/v1/profile/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDA3NDc5MzksImV4cCI6MTc0MDgzNDMzOSwiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiZmE4YzY2MTctMzNmYi00NmFkLTg4NDQtNDMyN2EyMjlhYzhmIiwidXNlcm5hbWUiOiJzYW5qYXI5MDIxMDVAZ21haWwuY29tIiwicm9sZSI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl19.TCw7WcHijpyQUPYd_GirC4nI2OjjZ7f8au4Q88e8X0wBUlhRiLBPjGlTmm8AbiHI
Accept-Language: uz

{
"status": "ACTIVE",
  "role": "ROLE_ADMIN"
}

### update profile status
PUT localhost:8080/api/v1/profile/changeStatus/73d0148d-a509-4c45-b0f1-16d58761f6e6
Content-Type:application/json
Accept-Language: uz
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDA3NDM4NDMsImV4cCI6MTc0MDc1MTA0MywiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiZmE4YzY2MTctMzNmYi00NmFkLTg4NDQtNDMyN2EyMjlhYzhmIiwidXNlcm5hbWUiOiJzYW5qYXI5MDIxMDVAZ21haWwuY29tIiwicm9sZSI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl19.r9LHKb82xFuaiJ-aFTHYpxQoS6z3Z-Z7cjrA7XGX6uFqLbh6qRuxPPSa4BxT2f1R

{
  "status": "ACTIVE"
}

### delete profile
DELETE localhost:8080/api/v1/profile/73d0148d-a509-4c45-b0f1-16d58761f6e6
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3NDA3NDM4NDMsImV4cCI6MTc0MDc1MTA0MywiaXNzIjoiR2l5YmF0IHRlc3QgcG9ydGFsaSIsImlkIjoiZmE4YzY2MTctMzNmYi00NmFkLTg4NDQtNDMyN2EyMjlhYzhmIiwidXNlcm5hbWUiOiJzYW5qYXI5MDIxMDVAZ21haWwuY29tIiwicm9sZSI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl19.r9LHKb82xFuaiJ-aFTHYpxQoS6z3Z-Z7cjrA7XGX6uFqLbh6qRuxPPSa4BxT2f1R
